name: planet
channels:
  - anaconda
  - conda-forge
dependencies:
  - plotly
  - pytorch-gpu
  - torchvision
  - tqdm
  - pip
  - tensorflow-gpu
  - pip:
    - gym
    - opencv-python
    - mlagents
    - gym_unity
